export const COLORS = {
  primary: "cyan",
  accent: "blue",
  success: "green",
  warning: "yellow",
  error: "red",
  muted: "gray",
  modeBuild: "blue",
  modeDiscuss: "purple",
  modePlan: "orange",
  text: "white",
  dimText: "#666666",
  appBackground: "#000000",
  panelShade: "#101010",
  sidebarShade: "#181818",
  codeBlockShade: "#1a1a1a",
  codeBlockBorder: "#333333",
  statusBarShade: "#202020",
  inlineChipShade: "#2a2a2a",
  inputShade: "#2b2b2b",
} as const

export const ICONS = {
  logo: "◆",
  user: "❯",
  assistant: "◈",
  tool: "⚙",
  success: "✓",
  error: "✗",
  warning: "⚠",
  chevron: "›",
  dot: "●",
  arrow: "→",
  check: "✓",
  cross: "✗",
  hourglass: "⏳",
  sparkle: "✦",
} as const

export const ASCII_BANNER = [
  "",
  "  ██╗   ██╗██╗███████╗███████╗███████╗███████╗",
  "  ██║   ██║██║██╔════╝██╔═══██╗██╔═══██╗██╔════╝",
  "  ██║   ██║██║██║     ██║   ██║██║   ██║█████╗  ",
  "  ╚██╗ ██╔╝██║██║     ██║   ██║██║   ██║██╔══╝  ",
  "   ╚████╔╝ ██║╚██████╗╚██████╔╝████████║███████╗",
  "    ╚═══╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝",
  "",
].join("\n")
